const data = {
  users: [
    {
      name: "Nurul Amin",
      email: "amin@gmail.com",
      password: "Amin@1234",
      phone: "017456845",
      address: "Sylhet, BD",
      image: "default.png",
    },
    {
      name: "Khairul Amin",
      email: "kamin@gmail.com",
      password: "Amin@1234",
      phone: "017966854845",
      address: "Sylhet, GP",
      image: "default.png",
    },
    {
      name: "Mahia Ahmed",
      email: "mahia@gmail.com",
      password: "Amin@1234",
      phone: "0146588446565",
      address: "Sylhet",
      image: "default.png",
    },
  ],

  products: [
    {
      name: "iPhone 11",
      slug: "iphone-11",
      description: "apple phone dess",
      price: 699.99,
      quantity: 50,
      sold: 25,
      shipping: 0,
      image: "iphone-11.jpg",
      category: "64db990200d90eb470be5e27",
    },
    {
      name: "Redmi 11",
      slug: "redmi-11",
      description: " xahowmmi phone ",
      price: 345.99,
      quantity: 40,
      sold: 2,
      shipping: 0,
      image: "redmi11.jpg",
      category: "64db98d900d90eb470be5e23",
    },
    {
      name: "Samsung Galuxy",
      slug: "samsung galuxy",
      description: "samsung galagy phone",
      price: 445.99,
      quantity: 30,
      sold: 2,
      shipping: 0,
      image: "samsung1.jpg",
      category: "64db98ef00d90eb470be5e25",
    },
    {
      name: "HP laptop",
      slug: "hp-laptop",
      description: "hp laptop",
      price: 345.99,
      quantity: 30,
      sold: 2,
      shipping: 0,
      image: "hp1.jpg",
      category: "64db991000d90eb470be5e29",
    },
  ],
};

module.exports = data;
